spring.datasource.url=jdbc:postgresql://your-db-host:5432/your-db-name
spring.datasource.username=your-db-username
spring.datasource.password=your-db-password

spring.jpa.show-sql=true
app.cors.allowed-origins=http://localhost:3000
